# Generated by Django 4.2.2 on 2023-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantas',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
    ]
